=== Patrick-UNCG/Solvd-HW/JDBCTest/src/main/XML/Region.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="regions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="region" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="regionId" type="xs:positiveInteger"/>
                            <xs:element name="regionName" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Patrick-UNCG/Solvd-HW/JDBCTest/src/main/XML/Region.xml
<?xml version="1.0" encoding="UTF-8"?>
<regions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Region.xsd">
    <region>
        <regionId>1</regionId>
        <regionName>North America</regionName>
    </region>
    <region>
        <regionId>2</regionId>
        <regionName>South America</regionName>
    </region>
    <region>
        <regionId>3</regionId>
        <regionName>Europe</regionName>
    </region>
</regions>
