=== Patrick-UNCG/Solvd-HW/JDBCTest/src/main/XML/Student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="studentId" type="xs:positiveInteger"/>
                            <xs:element name="studentFirstName" type="xs:string"/>
                            <xs:element name="studentLastName" type="xs:string"/>
                            <xs:element name="studentUniversityId" type="xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Patrick-UNCG/Solvd-HW/JDBCTest/src/main/XML/Student.xml
<?xml version="1.0" encoding="UTF-8"?>

<students
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Student.xsd">
    <student>
        <studentId>1</studentId>
        <studentFirstName>John</studentFirstName>
        <studentLastName>Smith</studentLastName>
        <studentUniversityId>1</studentUniversityId>
    </student>
    <student>
        <studentId>2</studentId>
        <studentFirstName>Mary</studentFirstName>
        <studentLastName>Johnson</studentLastName>
        <studentUniversityId>1</studentUniversityId>
    </student>
    <student>
        <studentId>3</studentId>
        <studentFirstName>Jesse</studentFirstName>
        <studentLastName>Robinson</studentLastName>
        <studentUniversityId>1</studentUniversityId>
    </student>
    <student>
        <studentId>4</studentId>
        <studentFirstName>Susie</studentFirstName>
        <studentLastName>Le</studentLastName>
        <studentUniversityId>1</studentUniversityId>
    </student>
</students>
