=== Patrick-UNCG/Solvd-HW/JDBCTest/src/main/resources/XML/Courses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="courses">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="course" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="courseId" type="xs:positiveInteger"/>
                            <xs:element name="courseName" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Patrick-UNCG/Solvd-HW/JDBCTest/src/main/XML/Courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Courses.xsd">
    <course>
        <courseId>1</courseId>
        <courseName>Biology</courseName>
    </course>
    <course>
        <courseId>2</courseId>
        <courseName>Calculus</courseName>
    </course>
    <course>
        <courseId>3</courseId>
        <courseName>History</courseName>
    </course>
</courses>
