=== Patrick-UNCG/Solvd-HW/JDBCTest/src/main/resources/XML/Professor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="professors">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="professor" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="professorId" type="xs:positiveInteger"/>
                            <xs:element name="professorFirstName" type="xs:string"/>
                            <xs:element name="professorLastName" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Patrick-UNCG/Solvd-HW/JDBCTest/src/main/XML/Professor.xml
<?xml version="1.0" encoding="UTF-8"?>
<professors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Professor.xsd">
    <professor>
        <professorId>1</professorId>
        <professorFirstName>Jerome</professorFirstName>
        <professorLastName>Dilly</professorLastName>
    </professor>
    <professor>
        <professorId>2</professorId>
        <professorFirstName>Gianna</professorFirstName>
        <professorLastName>Steinkamp</professorLastName>
    </professor>
    <professor>
        <professorId>3</professorId>
        <professorFirstName>Tara</professorFirstName>
        <professorLastName>Cook</professorLastName>
    </professor>
    <professor>
        <professorId>4</professorId>
        <professorFirstName>D</professorFirstName>
        <professorLastName>Bean</professorLastName>
    </professor>

</professors>
