=== Patrick-UNCG/Solvd-HW/JDBCTest/src/main/resources/XML/School.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="school">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="students">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="student" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="studentId" type="xs:positiveInteger"/>
                                        <xs:element name="studentFirstName" type="xs:string"/>
                                        <xs:element name="studentLastName" type="xs:string"/>
                                        <xs:element name="studentUniversityId" type="xs:positiveInteger"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="professors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="professor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="professorId" type="xs:positiveInteger"/>
                                        <xs:element name="professorFirstName" type="xs:string"/>
                                        <xs:element name="professorLastName" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="courses">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="course" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="courseId" type="xs:positiveInteger"/>
                                        <xs:element name="courseName" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="universities">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="university" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="universityId" type="xs:positiveInteger"/>
                                        <xs:element name="universityName" type="xs:string"/>
                                        <xs:element name="universityAddressId" type="xs:int"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="regions">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="region" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="regionId" type="xs:positiveInteger"/>
                                        <xs:element name="regionName" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Patrick-UNCG/Solvd-HW/JDBCTest/src/main/resources/XML/School.xml
<school xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="School.xsd">
    <students>
        <student>
            <studentId>1</studentId>
            <studentFirstName>John</studentFirstName>
            <studentLastName>Smith</studentLastName>
            <studentUniversityId>1</studentUniversityId>
        </student>
        <student>
            <studentId>2</studentId>
            <studentFirstName>Mary</studentFirstName>
            <studentLastName>Johnson</studentLastName>
            <studentUniversityId>1</studentUniversityId>
        </student>
        <student>
            <studentId>3</studentId>
            <studentFirstName>Jesse</studentFirstName>
            <studentLastName>Robinson</studentLastName>
            <studentUniversityId>1</studentUniversityId>
        </student>
        <student>
            <studentId>4</studentId>
            <studentFirstName>Susie</studentFirstName>
            <studentLastName>Le</studentLastName>
            <studentUniversityId>1</studentUniversityId>
        </student>
    </students>
    <professors>
        <professor>
            <professorId>1</professorId>
            <professorFirstName>Jerome</professorFirstName>
            <professorLastName>Dilly</professorLastName>
        </professor>
        <professor>
            <professorId>2</professorId>
            <professorFirstName>Gianna</professorFirstName>
            <professorLastName>Steinkamp</professorLastName>
        </professor>
        <professor>
            <professorId>3</professorId>
            <professorFirstName>Tara</professorFirstName>
            <professorLastName>Cook</professorLastName>
        </professor>
        <professor>
            <professorId>4</professorId>
            <professorFirstName>D</professorFirstName>
            <professorLastName>Bean</professorLastName>
        </professor>
    </professors>
    <courses>
        <course>
            <courseId>1</courseId>
            <courseName>Biology</courseName>
        </course>
        <course>
            <courseId>2</courseId>
            <courseName>Calculus</courseName>
        </course>
        <course>
            <courseId>3</courseId>
            <courseName>History</courseName>
        </course>
    </courses>
    <universities>
        <university>
            <universityId>1</universityId>
            <universityName>Harvard</universityName>
            <universityAddressId>1</universityAddressId>
        </university>
    </universities>
    <regions>
        <region>
            <regionId>1</regionId>
            <regionName>North America</regionName>
        </region>
        <region>
            <regionId>2</regionId>
            <regionName>South America</regionName>
        </region>
        <region>
            <regionId>3</regionId>
            <regionName>Europe</regionName>
        </region>
    </regions>
</school>
